version: 2.0
jobs:
  rtems:
    docker:
      - image: sergiusthebest/rtems-arm-rasberrypi-ci:latest
    steps:
      - checkout
      - run: cmake -H. -Bbuild -DCMAKE_TOOLCHAIN_FILE=$CMAKE_TOOLCHAIN_FILE && cd build && make -j
  platformio:
    docker:
      - image: ghcr.io/sergiusthebest/platformio-ci:latest
    steps:
      - checkout
      - run: pio run -d samples/Arduino
  android-ndk:
    docker:
      - image: sergiusthebest/android-ndk-ci:latest
    steps:
      - checkout
      - run: cmake -H. -Bbuild -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-30 -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake && cd build && make -j
workflows:
  version: 2
  workflow:
    jobs:
      - rtems
      - platformio
      - android-ndk
